project:
  type: website
  output-dir: docs

website:
  title: "BCB504Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/ronald-bentil-242279108
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

